In [3]:
from envs.card import Card, Rank
from envs.deck import Deck

deck = Deck()
deck.cards

[🌰8,
 🌰U,
 🌼O,
 🌰10,
 🔔A,
 🌰O,
 🛡️ 6,
 🔔U,
 🌼K,
 🌰9,
 🛡️ 9,
 🔔10,
 🌼6,
 🌼U,
 🌰A,
 🌼10,
 🔔7,
 🔔6,
 🛡️ 7,
 🌰7,
 🌼9,
 🔔K,
 🔔O,
 🔔9,
 🛡️ A,
 🌰K,
 🛡️ 8,
 🛡️ K,
 🌰6,
 🛡️ O,
 🌼7,
 🌼8,
 🔔8,
 🛡️ 10,
 🌼A,
 🛡️ U]

In [4]:
deck.order_deck()

deck.cards

[🌼6,
 🌼7,
 🌼8,
 🌼9,
 🌼10,
 🌼U,
 🌼O,
 🌼K,
 🌼A,
 🛡️ 6,
 🛡️ 7,
 🛡️ 8,
 🛡️ 9,
 🛡️ 10,
 🛡️ U,
 🛡️ O,
 🛡️ K,
 🛡️ A,
 🌰6,
 🌰7,
 🌰8,
 🌰9,
 🌰10,
 🌰U,
 🌰O,
 🌰K,
 🌰A,
 🔔6,
 🔔7,
 🔔8,
 🔔9,
 🔔10,
 🔔U,
 🔔O,
 🔔K,
 🔔A]

In [2]:
trick = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}

for idx, card in enumerate(trick.values()):
    print(idx)
    print(card)

0
0
1
1
2
2
3
3


In [4]:
from envs.env import JassEnv

players = {"P1": "random", "P2": "greedy", "P3": "random"}
# Create game instance and play one round of Jass
env = JassEnv(starting_player_id=1, players=players)
state = env.reset()

P1 played 🌼O
P2 played 🌼8
P3 played 🌼9
[[[1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.
   1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1.
   0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [22]:
import numpy as np

state = np.zeros((4, 4, 36))

state[0, 0, 24] = 1
state[0, 0, 34] = 1
state[0, 0, 10] = 1
state[1, 2, 15] = 1

index = np.where(state[2, :, :] == 1)[1]
print(index[0])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [26]:
from envs.trick import Trick

t1 = Trick(1)
t1.trick["P1"] = "nlel"

print(t1.trick)

t1 = Trick(1)

print(t1.trick)

{'P0': None, 'P1': 'nlel', 'P2': None, 'P3': None}
{'P0': None, 'P1': None, 'P2': None, 'P3': None}


In [27]:
import numpy as np

arr = np.array([5, 12, 3, 25, 8, 0, 9, 30, 7])  # Example array

filtered_arr = arr[(arr >= 0) & (arr <= 8)]
print(filtered_arr)

[5 3 8 0 7]


In [32]:
def func(hand):
    valid_hand = hand
    return valid_hand if valid_hand else "lel"

In [45]:
state = np.zeros((4, 4, 4), dtype=int)

state[0, 2, 3] = 1
state[0, 0, 2] = 1

state[1, 1, 2] = 1
state[1, 0, 3] = 1

state[2, 0, 3] = 1
state[2, 1, 1] = 1

print(state)

state[3, :, :] = state[1, :, :] | state[3, :, :]
state[1, :, :] = 0

state[3, :, :] = state[2, :, :] | state[3, :, :]
state[2, :, :] = 0

print(state)

[[[0 0 1 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 0 0]]

 [[0 0 0 1]
  [0 0 1 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 1]
  [0 1 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[0 0 1 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 1]
  [0 1 1 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [43]:
import numpy as np

# Example 3D array
arr = np.zeros((4, 4, 36), dtype=int)

# Assuming arr has some data
arr[1, 0, 5] = 1  # Example data in the 2nd row (index 1)
arr[3, 0, 5] = 1  # Example data in the 4th row (index 3)

# Perform element-wise OR between arr[1, :, :] and arr[3, :, :]
arr[3, :, :] = arr[1, :, :] | arr[3, :, :]

print(arr[3, :, :])


[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [22]:
from collections import namedtuple
from utils import ReplayMemory
import numpy as np


memory = ReplayMemory(1000)

for i in range(100):
    state = np.random.rand(4, 4, 36)
    action = np.random.randint(0, 35)
    reward = np.random.rand()
    next_state = np.random.rand(4, 4, 36)
    done = False
    memory.push(state, action, reward, next_state, done)

states, actions, rewards, next_states, dones = memory.sample(5, split_transitions=True)

In [31]:
dones

tensor([0., 0., 0., 0., 0.])

In [68]:
import numpy as np
import torch

# Sample list with integers and np.ndarray elements of shape (3, 4, 36)
state = [np.random.rand(3, 4, 36), 2, 0]

card_distribution = state[0]
leading_player_id = state[1]  # Player who played the first card in the trick
play_style = state[2]

flattened_state = np.concatenate([np.ravel(card_distribution), np.eye(4)[leading_player_id], np.eye(7)[play_style]])
state = torch.tensor(flattened_state, dtype=torch.float).reshape(1, -1)

print(state)

tensor([[0.2627, 0.3538, 0.7330, 0.0794, 0.9996, 0.5533, 0.5827, 0.2839, 0.9667,
         0.4710, 0.7368, 0.8662, 0.2876, 0.9145, 0.1615, 0.6291, 0.8013, 0.2216,
         0.7836, 0.1251, 0.7408, 0.4388, 0.4810, 0.0318, 0.8823, 0.8841, 0.3909,
         0.2951, 0.6111, 0.0376, 0.9160, 0.0106, 0.5979, 0.2428, 0.7499, 0.1121,
         0.7618, 0.7970, 0.4367, 0.9152, 0.4834, 0.1543, 0.6906, 0.8065, 0.5187,
         0.2414, 0.6142, 0.0561, 0.9257, 0.5726, 0.2431, 0.9832, 0.4120, 0.7830,
         0.6820, 0.3449, 0.9792, 0.3853, 0.8299, 0.6535, 0.4859, 0.3436, 0.5629,
         0.5510, 0.4648, 0.3291, 0.5803, 0.2754, 0.2618, 0.6265, 0.4055, 0.7241,
         0.7346, 0.1448, 0.6072, 0.5419, 0.8091, 0.9321, 0.7157, 0.6490, 0.6734,
         0.3420, 0.1550, 0.2665, 0.5886, 0.1563, 0.1623, 0.2285, 0.0997, 0.1196,
         0.7305, 0.7185, 0.4358, 0.6162, 0.9074, 0.8604, 0.9261, 0.7069, 0.9828,
         0.7114, 0.9739, 0.4621, 0.2288, 0.2982, 0.6320, 0.0877, 0.7759, 0.6496,
         0.1329, 0.2122, 0.4

In [64]:
3*4*36 + 4 + 7

443

In [70]:
dones = [False, True, False, False, True]
torch.tensor(dones, dtype=torch.float32)

tensor([0., 1., 0., 0., 1.])

In [5]:
import numpy as np

# Example 3D array
arr = np.zeros((3, 4, 36), dtype=int)
# Some elements are set to 1
arr[0, 0, 5] = 1
arr[0, 0, 1] = 1
arr[0, 0, 2] = 1
arr[0, 1, 10] = 1
arr[1, 2, 15] = 1
arr[2, 3, 20] = 1

# Get the indices of the elements that are set to 1
indices = np.where(arr[0, 0, :] == 1)
indices[0].tolist()

[1, 2, 5]