In [3]:
from envs.card import Card, Rank
from envs.deck import Deck

deck = Deck()
deck.cards

[🌰8,
 🌰U,
 🌼O,
 🌰10,
 🔔A,
 🌰O,
 🛡️ 6,
 🔔U,
 🌼K,
 🌰9,
 🛡️ 9,
 🔔10,
 🌼6,
 🌼U,
 🌰A,
 🌼10,
 🔔7,
 🔔6,
 🛡️ 7,
 🌰7,
 🌼9,
 🔔K,
 🔔O,
 🔔9,
 🛡️ A,
 🌰K,
 🛡️ 8,
 🛡️ K,
 🌰6,
 🛡️ O,
 🌼7,
 🌼8,
 🔔8,
 🛡️ 10,
 🌼A,
 🛡️ U]

In [4]:
deck.order_deck()

deck.cards

[🌼6,
 🌼7,
 🌼8,
 🌼9,
 🌼10,
 🌼U,
 🌼O,
 🌼K,
 🌼A,
 🛡️ 6,
 🛡️ 7,
 🛡️ 8,
 🛡️ 9,
 🛡️ 10,
 🛡️ U,
 🛡️ O,
 🛡️ K,
 🛡️ A,
 🌰6,
 🌰7,
 🌰8,
 🌰9,
 🌰10,
 🌰U,
 🌰O,
 🌰K,
 🌰A,
 🔔6,
 🔔7,
 🔔8,
 🔔9,
 🔔10,
 🔔U,
 🔔O,
 🔔K,
 🔔A]

In [2]:
trick = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}

for idx, card in enumerate(trick.values()):
    print(idx)
    print(card)

0
0
1
1
2
2
3
3


In [4]:
from envs.env import JassEnv

players = {"P1": "random", "P2": "greedy", "P3": "random"}
# Create game instance and play one round of Jass
env = JassEnv(starting_player_id=1, players=players)
state = env.reset()

P1 played 🌼O
P2 played 🌼8
P3 played 🌼9
[[[1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.
   1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1.
   0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [22]:
import numpy as np

state = np.zeros((4, 4, 36))

state[0, 0, 24] = 1
state[0, 0, 34] = 1
state[0, 0, 10] = 1
state[1, 2, 15] = 1

index = np.where(state[2, :, :] == 1)[1]
print(index[0])

IndexError: index 0 is out of bounds for axis 0 with size 0

In [26]:
from envs.trick import Trick

t1 = Trick(1)
t1.trick["P1"] = "nlel"

print(t1.trick)

t1 = Trick(1)

print(t1.trick)

{'P0': None, 'P1': 'nlel', 'P2': None, 'P3': None}
{'P0': None, 'P1': None, 'P2': None, 'P3': None}


In [27]:
import numpy as np

arr = np.array([5, 12, 3, 25, 8, 0, 9, 30, 7])  # Example array

filtered_arr = arr[(arr >= 0) & (arr <= 8)]
print(filtered_arr)

[5 3 8 0 7]


In [32]:
def func(hand):
    valid_hand = hand
    return valid_hand if valid_hand else "lel"

In [45]:
state = np.zeros((4, 4, 4), dtype=int)

state[0, 2, 3] = 1
state[0, 0, 2] = 1

state[1, 1, 2] = 1
state[1, 0, 3] = 1

state[2, 0, 3] = 1
state[2, 1, 1] = 1

print(state)

state[3, :, :] = state[1, :, :] | state[3, :, :]
state[1, :, :] = 0

state[3, :, :] = state[2, :, :] | state[3, :, :]
state[2, :, :] = 0

print(state)

[[[0 0 1 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 0 0]]

 [[0 0 0 1]
  [0 0 1 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 1]
  [0 1 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[0 0 1 0]
  [0 0 0 0]
  [0 0 0 1]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 1]
  [0 1 1 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [43]:
import numpy as np

# Example 3D array
arr = np.zeros((4, 4, 36), dtype=int)

# Assuming arr has some data
arr[1, 0, 5] = 1  # Example data in the 2nd row (index 1)
arr[3, 0, 5] = 1  # Example data in the 4th row (index 3)

# Perform element-wise OR between arr[1, :, :] and arr[3, :, :]
arr[3, :, :] = arr[1, :, :] | arr[3, :, :]

print(arr[3, :, :])


[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
